version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: balsampada-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: balsampada-lms
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - balsampada-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: balsampada-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/balsampada-lms?authSource=admin
      JWT_SECRET: your_super_secret_jwt_key_change_this_in_production
      JWT_EXPIRE: 7d
      CLIENT_URL: http://localhost:3000
    depends_on:
      - mongodb
    volumes:
      - ./backend/uploads:/app/uploads
    networks:
      - balsampada-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: balsampada-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:5000/api
    depends_on:
      - backend
    networks:
      - balsampada-network

volumes:
  mongodb_data:

networks:
  balsampada-network:
    driver: bridge